### ISSUE TITLE
output exception

### ISSUE THREAD

**Issue by HaosenSUN** [255BITS/diffusion-evolver#1]
Ask for help: The model gradually ’degenerates‘？ the output is almost blank after step-3, it seems that the Settings of the sample and the Settings of the model do not match

The following is the configuration for the specific Settings:
'model_list': models:
  - model: /home/lujunli/code-haosen/diffusion-evolver/model/model_a.safetensors
  - model: /home/lujunli/code-haosen/diffusion-evolver/model/model_b.safetensors
  - model: /home/lujunli/code-haosen/diffusion-evolver/model/model_a.safetensors
 '-eval_file':
T-Rex wearing aviator sunglasses, posing in front of a diffusion-generated Jurassic landscape, 80s vaporwave style, 4K

 parser.add_argument('-seed', dest='seed', type=int, default=None, help='Random seed')
    parser.add_argument('-cycles', dest='cycles', type=int, default=10, help='Number of evolutionary cycles')
    parser.add_argument('-elite', dest='elite', type=int, default=5, help='Number of elite candidates to keep every iteration')
    parser.add_argument('-parents', dest='parents', type=int, default=2, help='Number of parents for each child')
    parser.add_argument('-population', dest='population', type=int, default=20, help='Size of population')
    parser.add_argument('-mutation', dest='mutation', type=float, default=0.05, help='Chance of mutation')
parser.add_argument('-vlm', dest='vlm', type=str, default="llava", help='The vlm to use. claude or llava')

result(step-9.yaml):
models:
- model: evolve_output_01/e0499463-2a5d-4ef4-a30a-9a49d0ca0df6.safetensors
  p: 0.26354774694213234
  lambda: 2.808852670906563
  generation: 10
- model: evolve_output_01/dcd8ddd9-3a5b-401d-b8c8-51a0ed5edfde.safetensors
  p: 0.26354774694213234
  lambda: 2.808852670906563
  generation: 10
- model: evolve_output_01/06b8bf17-4525-4cfe-9b02-1e2fdaaf8ef6.safetensors
  p: 0.43883847775185836
  lambda: 1.8051909019753825
  generation: 10
- model: evolve_output_01/ca0f671b-c4f5-4b86-8f01-007225bc3ff2.safetensors
  p: 0.43883847775185836
  lambda: 1.8051909019753825
  generation: 10
- model: evolve_output_01/f8299136-860a-45e0-ab36-41b861a3b21f.safetensors
  p: 0.26354774694213234
  lambda: 2.808852670906563
  generation: 10
images output:
![merged_image](https://github.com/255BITS/diffusion-evolver/assets/103928629/4e6b8766-0ef0-4b92-8325-eded563a8237)

**Comment by HaosenSUN** [comment]
also, there is a warnings.warn(f'for {key}: copying from a non-meta parameter in the checkpoint to a meta '
/home/lujunli/miniconda3/envs/evolver/lib/python3.9/site-packages/torch/nn/modules/module.py:2025: UserWarning: for vision_model.encoder.layers.23.self_attn.q_proj.weight: copying from a non-meta parameter in the checkpoint to a meta parameter in the current model, which is a no-op. (Did you mean to pass `assign=True` to assign items in the state dictionary to their corresponding key in the module instead of copying them in place?)

**Comment by martyn** [comment]
Hi, the sources of degeneration in my experience are:
- too high lambda values
- incompatible initial models

You can try to lower the lambda values for longer running processes. For the 20 step I set it between 0.8 and 1.2 but it depends on the models, YMMV. I am not sure why the VLM isn't stopping the degeneration.

As for the warning, I haven't seen it before. Perhaps it's a torch version issue?
